// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: grpc_webnext.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A single WebSocket message. Exactly one field of `kind` is set.
// Keepalive is NOT an application frame: it uses native WebSocket ping/pong
// control frames (RFC 6455 §5.5.2), which browsers auto-answer and which generate
// the wire traffic that keeps idle-timeout proxies from dropping a quiet stream.
// Field numbers 6/7 held the removed app-level Ping/Pong and are reserved so they
// are never reused.
type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Frame_Subscribe
	//	*Frame_Message
	//	*Frame_HalfClose
	//	*Frame_Trailer
	//	*Frame_Reset_
	//	*Frame_Header
	Kind          isFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_grpc_webnext_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_webnext_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_grpc_webnext_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetKind() isFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Frame) GetSubscribe() *Subscribe {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *Frame) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *Frame) GetHalfClose() *HalfClose {
	if x != nil {
		if x, ok := x.Kind.(*Frame_HalfClose); ok {
			return x.HalfClose
		}
	}
	return nil
}

func (x *Frame) GetTrailer() *Trailer {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Trailer); ok {
			return x.Trailer
		}
	}
	return nil
}

func (x *Frame) GetReset_() *Reset {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Reset_); ok {
			return x.Reset_
		}
	}
	return nil
}

func (x *Frame) GetHeader() *Header {
	if x != nil {
		if x, ok := x.Kind.(*Frame_Header); ok {
			return x.Header
		}
	}
	return nil
}

type isFrame_Kind interface {
	isFrame_Kind()
}

type Frame_Subscribe struct {
	Subscribe *Subscribe `protobuf:"bytes,1,opt,name=subscribe,proto3,oneof"` // open the stream (client -> server)
}

type Frame_Message struct {
	Message *Message `protobuf:"bytes,2,opt,name=message,proto3,oneof"` // one gRPC message, either direction
}

type Frame_HalfClose struct {
	HalfClose *HalfClose `protobuf:"bytes,3,opt,name=half_close,json=halfClose,proto3,oneof"` // client done sending (client -> server)
}

type Frame_Trailer struct {
	Trailer *Trailer `protobuf:"bytes,4,opt,name=trailer,proto3,oneof"` // stream end + status (server -> client)
}

type Frame_Reset_ struct {
	Reset_ *Reset `protobuf:"bytes,5,opt,name=reset,proto3,oneof"` // abort the stream, either direction
}

type Frame_Header struct {
	Header *Header `protobuf:"bytes,8,opt,name=header,proto3,oneof"` // initial response metadata (server -> client)
}

func (*Frame_Subscribe) isFrame_Kind() {}

func (*Frame_Message) isFrame_Kind() {}

func (*Frame_HalfClose) isFrame_Kind() {}

func (*Frame_Trailer) isFrame_Kind() {}

func (*Frame_Reset_) isFrame_Kind() {}

func (*Frame_Header) isFrame_Kind() {}

// One metadata entry. Binary values (keys ending in "-bin") use `bin_value`.
type Metadatum struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Metadatum_AsciiValue
	//	*Metadatum_BinValue
	Value         isMetadatum_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadatum) Reset() {
	*x = Metadatum{}
	mi := &file_grpc_webnext_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadatum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadatum) ProtoMessage() {}

func (x *Metadatum) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_webnext_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadatum.ProtoReflect.Descriptor instead.
func (*Metadatum) Descriptor() ([]byte, []int) {
	return file_grpc_webnext_proto_rawDescGZIP(), []int{1}
}

func (x *Metadatum) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Metadatum) GetValue() isMetadatum_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Metadatum) GetAsciiValue() string {
	if x != nil {
		if x, ok := x.Value.(*Metadatum_AsciiValue); ok {
			return x.AsciiValue
		}
	}
	return ""
}

func (x *Metadatum) GetBinValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*Metadatum_BinValue); ok {
			return x.BinValue
		}
	}
	return nil
}

type isMetadatum_Value interface {
	isMetadatum_Value()
}

type Metadatum_AsciiValue struct {
	AsciiValue string `protobuf:"bytes,2,opt,name=ascii_value,json=asciiValue,proto3,oneof"`
}

type Metadatum_BinValue struct {
	BinValue []byte `protobuf:"bytes,3,opt,name=bin_value,json=binValue,proto3,oneof"`
}

func (*Metadatum_AsciiValue) isMetadatum_Value() {}

func (*Metadatum_BinValue) isMetadatum_Value() {}

// Open the stream. The first frame of the connection.
type Subscribe struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Method         string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`                                       // e.g. "/pkg.Service/Method"
	Headers        []*Metadatum           `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`                                     // request metadata
	TimeoutMillis  uint32                 `protobuf:"varint,3,opt,name=timeout_millis,json=timeoutMillis,proto3" json:"timeout_millis,omitempty"`   // gRPC deadline; 0 = none
	InitialPayload []byte                 `protobuf:"bytes,4,opt,name=initial_payload,json=initialPayload,proto3" json:"initial_payload,omitempty"` // optional first message (unary-style)
	Json           bool                   `protobuf:"varint,5,opt,name=json,proto3" json:"json,omitempty"`                                          // payloads are JSON (+json codec) not binary
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_grpc_webnext_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_webnext_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_grpc_webnext_proto_rawDescGZIP(), []int{2}
}

func (x *Subscribe) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Subscribe) GetHeaders() []*Metadatum {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Subscribe) GetTimeoutMillis() uint32 {
	if x != nil {
		return x.TimeoutMillis
	}
	return 0
}

func (x *Subscribe) GetInitialPayload() []byte {
	if x != nil {
		return x.InitialPayload
	}
	return nil
}

func (x *Subscribe) GetJson() bool {
	if x != nil {
		return x.Json
	}
	return false
}

// Initial response metadata, sent once before the first Message (if any).
type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       []*Metadatum           `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_grpc_webnext_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_webnext_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_grpc_webnext_proto_rawDescGZIP(), []int{3}
}

func (x *Header) GetHeaders() []*Metadatum {
	if x != nil {
		return x.Headers
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // a single encoded gRPC message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_grpc_webnext_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_webnext_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_grpc_webnext_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Client is done sending (a bare marker).
type HalfClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HalfClose) Reset() {
	*x = HalfClose{}
	mi := &file_grpc_webnext_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HalfClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HalfClose) ProtoMessage() {}

func (x *HalfClose) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_webnext_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HalfClose.ProtoReflect.Descriptor instead.
func (*HalfClose) Descriptor() ([]byte, []int) {
	return file_grpc_webnext_proto_rawDescGZIP(), []int{5}
}

// Stream completed. Carries gRPC status and trailing metadata.
type Trailer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // gRPC status code (0 = OK)
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	Trailers      []*Metadatum           `protobuf:"bytes,3,rep,name=trailers,proto3" json:"trailers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trailer) Reset() {
	*x = Trailer{}
	mi := &file_grpc_webnext_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trailer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trailer) ProtoMessage() {}

func (x *Trailer) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_webnext_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trailer.ProtoReflect.Descriptor instead.
func (*Trailer) Descriptor() ([]byte, []int) {
	return file_grpc_webnext_proto_rawDescGZIP(), []int{6}
}

func (x *Trailer) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Trailer) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *Trailer) GetTrailers() []*Metadatum {
	if x != nil {
		return x.Trailers
	}
	return nil
}

// Abort the stream. Also used by the server to reject it (e.g. feature disabled).
type Reset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // gRPC status code (e.g. CANCELLED, UNIMPLEMENTED)
	StatusMessage string                 `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reset) Reset() {
	*x = Reset{}
	mi := &file_grpc_webnext_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reset) ProtoMessage() {}

func (x *Reset) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_webnext_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reset.ProtoReflect.Descriptor instead.
func (*Reset) Descriptor() ([]byte, []int) {
	return file_grpc_webnext_proto_rawDescGZIP(), []int{7}
}

func (x *Reset) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Reset) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

var File_grpc_webnext_proto protoreflect.FileDescriptor

const file_grpc_webnext_proto_rawDesc = "" +
	"\n" +
	"\x12grpc_webnext.proto\x12\x0fgrpc.webnext.v1\"\xef\x02\n" +
	"\x05Frame\x12:\n" +
	"\tsubscribe\x18\x01 \x01(\v2\x1a.grpc.webnext.v1.SubscribeH\x00R\tsubscribe\x124\n" +
	"\amessage\x18\x02 \x01(\v2\x18.grpc.webnext.v1.MessageH\x00R\amessage\x12;\n" +
	"\n" +
	"half_close\x18\x03 \x01(\v2\x1a.grpc.webnext.v1.HalfCloseH\x00R\thalfClose\x124\n" +
	"\atrailer\x18\x04 \x01(\v2\x18.grpc.webnext.v1.TrailerH\x00R\atrailer\x12.\n" +
	"\x05reset\x18\x05 \x01(\v2\x16.grpc.webnext.v1.ResetH\x00R\x05reset\x121\n" +
	"\x06header\x18\b \x01(\v2\x17.grpc.webnext.v1.HeaderH\x00R\x06headerB\x06\n" +
	"\x04kindJ\x04\b\x06\x10\aJ\x04\b\a\x10\bR\x04pingR\x04pong\"h\n" +
	"\tMetadatum\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\vascii_value\x18\x02 \x01(\tH\x00R\n" +
	"asciiValue\x12\x1d\n" +
	"\tbin_value\x18\x03 \x01(\fH\x00R\bbinValueB\a\n" +
	"\x05value\"\xbd\x01\n" +
	"\tSubscribe\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x124\n" +
	"\aheaders\x18\x02 \x03(\v2\x1a.grpc.webnext.v1.MetadatumR\aheaders\x12%\n" +
	"\x0etimeout_millis\x18\x03 \x01(\rR\rtimeoutMillis\x12'\n" +
	"\x0finitial_payload\x18\x04 \x01(\fR\x0einitialPayload\x12\x12\n" +
	"\x04json\x18\x05 \x01(\bR\x04json\">\n" +
	"\x06Header\x124\n" +
	"\aheaders\x18\x01 \x03(\v2\x1a.grpc.webnext.v1.MetadatumR\aheaders\"#\n" +
	"\aMessage\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\v\n" +
	"\tHalfClose\"\x89\x01\n" +
	"\aTrailer\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\x126\n" +
	"\btrailers\x18\x03 \x03(\v2\x1a.grpc.webnext.v1.MetadatumR\btrailers\"O\n" +
	"\x05Reset\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessageb\x06proto3"

var (
	file_grpc_webnext_proto_rawDescOnce sync.Once
	file_grpc_webnext_proto_rawDescData []byte
)

func file_grpc_webnext_proto_rawDescGZIP() []byte {
	file_grpc_webnext_proto_rawDescOnce.Do(func() {
		file_grpc_webnext_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_webnext_proto_rawDesc), len(file_grpc_webnext_proto_rawDesc)))
	})
	return file_grpc_webnext_proto_rawDescData
}

var file_grpc_webnext_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_grpc_webnext_proto_goTypes = []any{
	(*Frame)(nil),     // 0: grpc.webnext.v1.Frame
	(*Metadatum)(nil), // 1: grpc.webnext.v1.Metadatum
	(*Subscribe)(nil), // 2: grpc.webnext.v1.Subscribe
	(*Header)(nil),    // 3: grpc.webnext.v1.Header
	(*Message)(nil),   // 4: grpc.webnext.v1.Message
	(*HalfClose)(nil), // 5: grpc.webnext.v1.HalfClose
	(*Trailer)(nil),   // 6: grpc.webnext.v1.Trailer
	(*Reset)(nil),     // 7: grpc.webnext.v1.Reset
}
var file_grpc_webnext_proto_depIdxs = []int32{
	2, // 0: grpc.webnext.v1.Frame.subscribe:type_name -> grpc.webnext.v1.Subscribe
	4, // 1: grpc.webnext.v1.Frame.message:type_name -> grpc.webnext.v1.Message
	5, // 2: grpc.webnext.v1.Frame.half_close:type_name -> grpc.webnext.v1.HalfClose
	6, // 3: grpc.webnext.v1.Frame.trailer:type_name -> grpc.webnext.v1.Trailer
	7, // 4: grpc.webnext.v1.Frame.reset:type_name -> grpc.webnext.v1.Reset
	3, // 5: grpc.webnext.v1.Frame.header:type_name -> grpc.webnext.v1.Header
	1, // 6: grpc.webnext.v1.Subscribe.headers:type_name -> grpc.webnext.v1.Metadatum
	1, // 7: grpc.webnext.v1.Header.headers:type_name -> grpc.webnext.v1.Metadatum
	1, // 8: grpc.webnext.v1.Trailer.trailers:type_name -> grpc.webnext.v1.Metadatum
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_grpc_webnext_proto_init() }
func file_grpc_webnext_proto_init() {
	if File_grpc_webnext_proto != nil {
		return
	}
	file_grpc_webnext_proto_msgTypes[0].OneofWrappers = []any{
		(*Frame_Subscribe)(nil),
		(*Frame_Message)(nil),
		(*Frame_HalfClose)(nil),
		(*Frame_Trailer)(nil),
		(*Frame_Reset_)(nil),
		(*Frame_Header)(nil),
	}
	file_grpc_webnext_proto_msgTypes[1].OneofWrappers = []any{
		(*Metadatum_AsciiValue)(nil),
		(*Metadatum_BinValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_webnext_proto_rawDesc), len(file_grpc_webnext_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpc_webnext_proto_goTypes,
		DependencyIndexes: file_grpc_webnext_proto_depIdxs,
		MessageInfos:      file_grpc_webnext_proto_msgTypes,
	}.Build()
	File_grpc_webnext_proto = out.File
	file_grpc_webnext_proto_goTypes = nil
	file_grpc_webnext_proto_depIdxs = nil
}
