// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: conformance.proto

// ============================================================================
// grpc-webnext conformance service.
//
// Every server implementation (Rust, Go, Node, …) serves THIS service over
// grpc-webnext. A language-neutral client driver runs the scenarios in
// `conformance/cases/*.yaml` against it and asserts the observed wire behavior.
// That matrix — {client drivers} × {server impls} × {transports} × {codecs} —
// is how five independent implementations of one wire protocol are kept from
// drifting. See `conformance/README.md`.
//
// The design mirrors connectrpc/conformance: the *request* carries a
// ResponseDefinition telling the server exactly how to respond (payload,
// status, metadata, timing), so a single generic service exercises every
// protocol feature without per-case server code.
// ============================================================================

package conformancepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConformanceService_Unary_FullMethodName        = "/grpc.webnext.conformance.v1.ConformanceService/Unary"
	ConformanceService_ServerStream_FullMethodName = "/grpc.webnext.conformance.v1.ConformanceService/ServerStream"
	ConformanceService_ClientStream_FullMethodName = "/grpc.webnext.conformance.v1.ConformanceService/ClientStream"
	ConformanceService_BidiStream_FullMethodName   = "/grpc.webnext.conformance.v1.ConformanceService/BidiStream"
)

// ConformanceServiceClient is the client API for ConformanceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConformanceServiceClient interface {
	// Unary over Fetch (or a single WebSocket stream). Echoes `payload` unless the
	// ResponseDefinition says otherwise; used for status, metadata, deadline, and
	// size-limit cases.
	Unary(ctx context.Context, in *UnaryRequest, opts ...grpc.CallOption) (*ConformancePayload, error)
	// Server streaming: emits ResponseDefinition.stream_messages in order, honoring
	// per-message `delay_ms`, then closes with ResponseDefinition.status.
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConformancePayload], error)
	// Client streaming: consumes the inbound stream, then returns one response built
	// from the ResponseDefinition on the FIRST request (later requests carry payload
	// only). `aggregate` reports what the server received.
	ClientStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ClientStreamRequest, ClientStreamResponse], error)
	// Bidi: for each inbound message, echoes one ConformancePayload back; closes with
	// the ResponseDefinition.status from the first request. Exercises interleaving,
	// half-close, and mid-stream Reset/cancel.
	BidiStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BidiStreamRequest, ConformancePayload], error)
}

type conformanceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConformanceServiceClient(cc grpc.ClientConnInterface) ConformanceServiceClient {
	return &conformanceServiceClient{cc}
}

func (c *conformanceServiceClient) Unary(ctx context.Context, in *UnaryRequest, opts ...grpc.CallOption) (*ConformancePayload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConformancePayload)
	err := c.cc.Invoke(ctx, ConformanceService_Unary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conformanceServiceClient) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConformancePayload], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConformanceService_ServiceDesc.Streams[0], ConformanceService_ServerStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ServerStreamRequest, ConformancePayload]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConformanceService_ServerStreamClient = grpc.ServerStreamingClient[ConformancePayload]

func (c *conformanceServiceClient) ClientStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ClientStreamRequest, ClientStreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConformanceService_ServiceDesc.Streams[1], ConformanceService_ClientStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientStreamRequest, ClientStreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConformanceService_ClientStreamClient = grpc.ClientStreamingClient[ClientStreamRequest, ClientStreamResponse]

func (c *conformanceServiceClient) BidiStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BidiStreamRequest, ConformancePayload], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConformanceService_ServiceDesc.Streams[2], ConformanceService_BidiStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BidiStreamRequest, ConformancePayload]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConformanceService_BidiStreamClient = grpc.BidiStreamingClient[BidiStreamRequest, ConformancePayload]

// ConformanceServiceServer is the server API for ConformanceService service.
// All implementations must embed UnimplementedConformanceServiceServer
// for forward compatibility.
type ConformanceServiceServer interface {
	// Unary over Fetch (or a single WebSocket stream). Echoes `payload` unless the
	// ResponseDefinition says otherwise; used for status, metadata, deadline, and
	// size-limit cases.
	Unary(context.Context, *UnaryRequest) (*ConformancePayload, error)
	// Server streaming: emits ResponseDefinition.stream_messages in order, honoring
	// per-message `delay_ms`, then closes with ResponseDefinition.status.
	ServerStream(*ServerStreamRequest, grpc.ServerStreamingServer[ConformancePayload]) error
	// Client streaming: consumes the inbound stream, then returns one response built
	// from the ResponseDefinition on the FIRST request (later requests carry payload
	// only). `aggregate` reports what the server received.
	ClientStream(grpc.ClientStreamingServer[ClientStreamRequest, ClientStreamResponse]) error
	// Bidi: for each inbound message, echoes one ConformancePayload back; closes with
	// the ResponseDefinition.status from the first request. Exercises interleaving,
	// half-close, and mid-stream Reset/cancel.
	BidiStream(grpc.BidiStreamingServer[BidiStreamRequest, ConformancePayload]) error
	mustEmbedUnimplementedConformanceServiceServer()
}

// UnimplementedConformanceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConformanceServiceServer struct{}

func (UnimplementedConformanceServiceServer) Unary(context.Context, *UnaryRequest) (*ConformancePayload, error) {
	return nil, status.Error(codes.Unimplemented, "method Unary not implemented")
}
func (UnimplementedConformanceServiceServer) ServerStream(*ServerStreamRequest, grpc.ServerStreamingServer[ConformancePayload]) error {
	return status.Error(codes.Unimplemented, "method ServerStream not implemented")
}
func (UnimplementedConformanceServiceServer) ClientStream(grpc.ClientStreamingServer[ClientStreamRequest, ClientStreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ClientStream not implemented")
}
func (UnimplementedConformanceServiceServer) BidiStream(grpc.BidiStreamingServer[BidiStreamRequest, ConformancePayload]) error {
	return status.Error(codes.Unimplemented, "method BidiStream not implemented")
}
func (UnimplementedConformanceServiceServer) mustEmbedUnimplementedConformanceServiceServer() {}
func (UnimplementedConformanceServiceServer) testEmbeddedByValue()                            {}

// UnsafeConformanceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConformanceServiceServer will
// result in compilation errors.
type UnsafeConformanceServiceServer interface {
	mustEmbedUnimplementedConformanceServiceServer()
}

func RegisterConformanceServiceServer(s grpc.ServiceRegistrar, srv ConformanceServiceServer) {
	// If the following call panics, it indicates UnimplementedConformanceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConformanceService_ServiceDesc, srv)
}

func _ConformanceService_Unary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConformanceServiceServer).Unary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConformanceService_Unary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConformanceServiceServer).Unary(ctx, req.(*UnaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConformanceService_ServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServerStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConformanceServiceServer).ServerStream(m, &grpc.GenericServerStream[ServerStreamRequest, ConformancePayload]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConformanceService_ServerStreamServer = grpc.ServerStreamingServer[ConformancePayload]

func _ConformanceService_ClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConformanceServiceServer).ClientStream(&grpc.GenericServerStream[ClientStreamRequest, ClientStreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConformanceService_ClientStreamServer = grpc.ClientStreamingServer[ClientStreamRequest, ClientStreamResponse]

func _ConformanceService_BidiStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConformanceServiceServer).BidiStream(&grpc.GenericServerStream[BidiStreamRequest, ConformancePayload]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConformanceService_BidiStreamServer = grpc.BidiStreamingServer[BidiStreamRequest, ConformancePayload]

// ConformanceService_ServiceDesc is the grpc.ServiceDesc for ConformanceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConformanceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.webnext.conformance.v1.ConformanceService",
	HandlerType: (*ConformanceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unary",
			Handler:    _ConformanceService_Unary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStream",
			Handler:       _ConformanceService_ServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientStream",
			Handler:       _ConformanceService_ClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BidiStream",
			Handler:       _ConformanceService_BidiStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "conformance.proto",
}
