// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: conformance.proto

// ============================================================================
// grpc-webnext conformance service.
//
// Every server implementation (Rust, Go, Node, …) serves THIS service over
// grpc-webnext. A language-neutral client driver runs the scenarios in
// `conformance/cases/*.yaml` against it and asserts the observed wire behavior.
// That matrix — {client drivers} × {server impls} × {transports} × {codecs} —
// is how five independent implementations of one wire protocol are kept from
// drifting. See `conformance/README.md`.
//
// The design mirrors connectrpc/conformance: the *request* carries a
// ResponseDefinition telling the server exactly how to respond (payload,
// status, metadata, timing), so a single generic service exercises every
// protocol feature without per-case server code.
// ============================================================================

package conformancepb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A REST-shaped unary request: every field is bindable from a URL.
type RestUnaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`                          // echoed back as ConformancePayload.payload (UTF-8)
	StatusCode    uint32                 `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // non-zero => terminal error, so REST error paths are testable
	StatusMessage string                 `protobuf:"bytes,3,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestUnaryRequest) Reset() {
	*x = RestUnaryRequest{}
	mi := &file_conformance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestUnaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestUnaryRequest) ProtoMessage() {}

func (x *RestUnaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conformance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestUnaryRequest.ProtoReflect.Descriptor instead.
func (*RestUnaryRequest) Descriptor() ([]byte, []int) {
	return file_conformance_proto_rawDescGZIP(), []int{0}
}

func (x *RestUnaryRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *RestUnaryRequest) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RestUnaryRequest) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

// A REST-shaped server-streaming request.
type RestStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`                          // emitted `count` times
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                             // bound from a query param, exercising uint32 coercion
	StatusCode    uint32                 `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // non-zero => terminal error after the messages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestStreamRequest) Reset() {
	*x = RestStreamRequest{}
	mi := &file_conformance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestStreamRequest) ProtoMessage() {}

func (x *RestStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conformance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestStreamRequest.ProtoReflect.Descriptor instead.
func (*RestStreamRequest) Descriptor() ([]byte, []int) {
	return file_conformance_proto_rawDescGZIP(), []int{1}
}

func (x *RestStreamRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *RestStreamRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RestStreamRequest) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

// How the server should respond. Present on unary requests and the first request of
// a streaming RPC; ignored on subsequent streaming requests.
type ResponseDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Terminal gRPC status. code 0 = OK. For streaming, applied after all messages.
	StatusCode    uint32 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusMessage string `protobuf:"bytes,2,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	// Metadata the server must emit. `headers` go out as initial metadata (WS Header
	// frame / Fetch response headers); `trailers` in the terminal Trailer/trailer block.
	Headers  []*Metadatum `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	Trailers []*Metadatum `protobuf:"bytes,4,rep,name=trailers,proto3" json:"trailers,omitempty"`
	// Unary/bidi: the payload to echo back. Streaming: see `stream_messages`.
	Payload []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	// Server-streaming: the ordered messages to emit before the terminal status.
	StreamMessages []*StreamMessage `protobuf:"bytes,6,rep,name=stream_messages,json=streamMessages,proto3" json:"stream_messages,omitempty"`
	// Sleep this long before producing the (first) response. Drives deadline tests:
	// set delay > the case's grpc-timeout and expect DEADLINE_EXCEEDED (code 4).
	DelayMs uint32 `protobuf:"varint,7,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	// If > 0, the unary/echo payload the server returns is this many bytes (server
	// fabricates it). Drives max-message-size cases (expect RESOURCE_EXHAUSTED = 8
	// when it exceeds the configured limit).
	OversizeResponseBytes uint32 `protobuf:"varint,8,opt,name=oversize_response_bytes,json=oversizeResponseBytes,proto3" json:"oversize_response_bytes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ResponseDefinition) Reset() {
	*x = ResponseDefinition{}
	mi := &file_conformance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDefinition) ProtoMessage() {}

func (x *ResponseDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_conformance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDefinition.ProtoReflect.Descriptor instead.
func (*ResponseDefinition) Descriptor() ([]byte, []int) {
	return file_conformance_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseDefinition) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ResponseDefinition) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *ResponseDefinition) GetHeaders() []*Metadatum {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ResponseDefinition) GetTrailers() []*Metadatum {
	if x != nil {
		return x.Trailers
	}
	return nil
}

func (x *ResponseDefinition) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ResponseDefinition) GetStreamMessages() []*StreamMessage {
	if x != nil {
		return x.StreamMessages
	}
	return nil
}

func (x *ResponseDefinition) GetDelayMs() uint32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

func (x *ResponseDefinition) GetOversizeResponseBytes() uint32 {
	if x != nil {
		return x.OversizeResponseBytes
	}
	return 0
}

type StreamMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	DelayMs       uint32                 `protobuf:"varint,2,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"` // sleep before emitting this message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessage) Reset() {
	*x = StreamMessage{}
	mi := &file_conformance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessage) ProtoMessage() {}

func (x *StreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_conformance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessage.ProtoReflect.Descriptor instead.
func (*StreamMessage) Descriptor() ([]byte, []int) {
	return file_conformance_proto_rawDescGZIP(), []int{3}
}

func (x *StreamMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamMessage) GetDelayMs() uint32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

type UnaryRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Payload            []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	ResponseDefinition *ResponseDefinition    `protobuf:"bytes,2,opt,name=response_definition,json=responseDefinition,proto3" json:"response_definition,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UnaryRequest) Reset() {
	*x = UnaryRequest{}
	mi := &file_conformance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryRequest) ProtoMessage() {}

func (x *UnaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conformance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryRequest.ProtoReflect.Descriptor instead.
func (*UnaryRequest) Descriptor() ([]byte, []int) {
	return file_conformance_proto_rawDescGZIP(), []int{4}
}

func (x *UnaryRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UnaryRequest) GetResponseDefinition() *ResponseDefinition {
	if x != nil {
		return x.ResponseDefinition
	}
	return nil
}

type ServerStreamRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ResponseDefinition *ResponseDefinition    `protobuf:"bytes,1,opt,name=response_definition,json=responseDefinition,proto3" json:"response_definition,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServerStreamRequest) Reset() {
	*x = ServerStreamRequest{}
	mi := &file_conformance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamRequest) ProtoMessage() {}

func (x *ServerStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conformance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamRequest.ProtoReflect.Descriptor instead.
func (*ServerStreamRequest) Descriptor() ([]byte, []int) {
	return file_conformance_proto_rawDescGZIP(), []int{5}
}

func (x *ServerStreamRequest) GetResponseDefinition() *ResponseDefinition {
	if x != nil {
		return x.ResponseDefinition
	}
	return nil
}

type ClientStreamRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Payload            []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	ResponseDefinition *ResponseDefinition    `protobuf:"bytes,2,opt,name=response_definition,json=responseDefinition,proto3" json:"response_definition,omitempty"` // honored on first request only
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClientStreamRequest) Reset() {
	*x = ClientStreamRequest{}
	mi := &file_conformance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamRequest) ProtoMessage() {}

func (x *ClientStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conformance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamRequest.ProtoReflect.Descriptor instead.
func (*ClientStreamRequest) Descriptor() ([]byte, []int) {
	return file_conformance_proto_rawDescGZIP(), []int{6}
}

func (x *ClientStreamRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientStreamRequest) GetResponseDefinition() *ResponseDefinition {
	if x != nil {
		return x.ResponseDefinition
	}
	return nil
}

type ClientStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *ConformancePayload    `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	ReceivedCount uint32                 `protobuf:"varint,2,opt,name=received_count,json=receivedCount,proto3" json:"received_count,omitempty"` // how many client messages the server saw
	ReceivedBytes uint64                 `protobuf:"varint,3,opt,name=received_bytes,json=receivedBytes,proto3" json:"received_bytes,omitempty"` // total payload bytes received
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientStreamResponse) Reset() {
	*x = ClientStreamResponse{}
	mi := &file_conformance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamResponse) ProtoMessage() {}

func (x *ClientStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conformance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamResponse.ProtoReflect.Descriptor instead.
func (*ClientStreamResponse) Descriptor() ([]byte, []int) {
	return file_conformance_proto_rawDescGZIP(), []int{7}
}

func (x *ClientStreamResponse) GetPayload() *ConformancePayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientStreamResponse) GetReceivedCount() uint32 {
	if x != nil {
		return x.ReceivedCount
	}
	return 0
}

func (x *ClientStreamResponse) GetReceivedBytes() uint64 {
	if x != nil {
		return x.ReceivedBytes
	}
	return 0
}

type BidiStreamRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Payload            []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	ResponseDefinition *ResponseDefinition    `protobuf:"bytes,2,opt,name=response_definition,json=responseDefinition,proto3" json:"response_definition,omitempty"` // honored on first request only
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BidiStreamRequest) Reset() {
	*x = BidiStreamRequest{}
	mi := &file_conformance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidiStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidiStreamRequest) ProtoMessage() {}

func (x *BidiStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conformance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidiStreamRequest.ProtoReflect.Descriptor instead.
func (*BidiStreamRequest) Descriptor() ([]byte, []int) {
	return file_conformance_proto_rawDescGZIP(), []int{8}
}

func (x *BidiStreamRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BidiStreamRequest) GetResponseDefinition() *ResponseDefinition {
	if x != nil {
		return x.ResponseDefinition
	}
	return nil
}

// What the server sends back. `request_info` lets a case assert what the server
// actually received (echoed metadata, timeout, codec), catching silent drops.
type ConformancePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	RequestInfo   *RequestInfo           `protobuf:"bytes,2,opt,name=request_info,json=requestInfo,proto3" json:"request_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConformancePayload) Reset() {
	*x = ConformancePayload{}
	mi := &file_conformance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConformancePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConformancePayload) ProtoMessage() {}

func (x *ConformancePayload) ProtoReflect() protoreflect.Message {
	mi := &file_conformance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConformancePayload.ProtoReflect.Descriptor instead.
func (*ConformancePayload) Descriptor() ([]byte, []int) {
	return file_conformance_proto_rawDescGZIP(), []int{9}
}

func (x *ConformancePayload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConformancePayload) GetRequestInfo() *RequestInfo {
	if x != nil {
		return x.RequestInfo
	}
	return nil
}

type ClientStreamResponseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceivedCount uint32                 `protobuf:"varint,1,opt,name=received_count,json=receivedCount,proto3" json:"received_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientStreamResponseInfo) Reset() {
	*x = ClientStreamResponseInfo{}
	mi := &file_conformance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientStreamResponseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStreamResponseInfo) ProtoMessage() {}

func (x *ClientStreamResponseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_conformance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStreamResponseInfo.ProtoReflect.Descriptor instead.
func (*ClientStreamResponseInfo) Descriptor() ([]byte, []int) {
	return file_conformance_proto_rawDescGZIP(), []int{10}
}

func (x *ClientStreamResponseInfo) GetReceivedCount() uint32 {
	if x != nil {
		return x.ReceivedCount
	}
	return 0
}

// Observed request context, echoed for assertions.
type RequestInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestHeaders []*Metadatum           `protobuf:"bytes,1,rep,name=request_headers,json=requestHeaders,proto3" json:"request_headers,omitempty"`
	TimeoutMillis  uint32                 `protobuf:"varint,2,opt,name=timeout_millis,json=timeoutMillis,proto3" json:"timeout_millis,omitempty"` // the grpc-timeout the server observed; 0 = none
	Json           bool                   `protobuf:"varint,3,opt,name=json,proto3" json:"json,omitempty"`                                        // did the request arrive on the +json codec
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestInfo) Reset() {
	*x = RequestInfo{}
	mi := &file_conformance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInfo) ProtoMessage() {}

func (x *RequestInfo) ProtoReflect() protoreflect.Message {
	mi := &file_conformance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInfo.ProtoReflect.Descriptor instead.
func (*RequestInfo) Descriptor() ([]byte, []int) {
	return file_conformance_proto_rawDescGZIP(), []int{11}
}

func (x *RequestInfo) GetRequestHeaders() []*Metadatum {
	if x != nil {
		return x.RequestHeaders
	}
	return nil
}

func (x *RequestInfo) GetTimeoutMillis() uint32 {
	if x != nil {
		return x.TimeoutMillis
	}
	return 0
}

func (x *RequestInfo) GetJson() bool {
	if x != nil {
		return x.Json
	}
	return false
}

// One metadata entry. Binary values (keys ending in "-bin") use `bin_value`.
type Metadatum struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Metadatum_AsciiValue
	//	*Metadatum_BinValue
	Value         isMetadatum_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadatum) Reset() {
	*x = Metadatum{}
	mi := &file_conformance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadatum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadatum) ProtoMessage() {}

func (x *Metadatum) ProtoReflect() protoreflect.Message {
	mi := &file_conformance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadatum.ProtoReflect.Descriptor instead.
func (*Metadatum) Descriptor() ([]byte, []int) {
	return file_conformance_proto_rawDescGZIP(), []int{12}
}

func (x *Metadatum) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Metadatum) GetValue() isMetadatum_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Metadatum) GetAsciiValue() string {
	if x != nil {
		if x, ok := x.Value.(*Metadatum_AsciiValue); ok {
			return x.AsciiValue
		}
	}
	return ""
}

func (x *Metadatum) GetBinValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*Metadatum_BinValue); ok {
			return x.BinValue
		}
	}
	return nil
}

type isMetadatum_Value interface {
	isMetadatum_Value()
}

type Metadatum_AsciiValue struct {
	AsciiValue string `protobuf:"bytes,2,opt,name=ascii_value,json=asciiValue,proto3,oneof"`
}

type Metadatum_BinValue struct {
	BinValue []byte `protobuf:"bytes,3,opt,name=bin_value,json=binValue,proto3,oneof"`
}

func (*Metadatum_AsciiValue) isMetadatum_Value() {}

func (*Metadatum_BinValue) isMetadatum_Value() {}

var File_conformance_proto protoreflect.FileDescriptor

const file_conformance_proto_rawDesc = "" +
	"\n" +
	"\x11conformance.proto\x12\x1bgrpc.webnext.conformance.v1\x1a\x1cgoogle/api/annotations.proto\"t\n" +
	"\x10RestUnaryRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\rR\n" +
	"statusCode\x12%\n" +
	"\x0estatus_message\x18\x03 \x01(\tR\rstatusMessage\"d\n" +
	"\x11RestStreamRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\rR\n" +
	"statusCode\"\xa4\x03\n" +
	"\x12ResponseDefinition\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12%\n" +
	"\x0estatus_message\x18\x02 \x01(\tR\rstatusMessage\x12@\n" +
	"\aheaders\x18\x03 \x03(\v2&.grpc.webnext.conformance.v1.MetadatumR\aheaders\x12B\n" +
	"\btrailers\x18\x04 \x03(\v2&.grpc.webnext.conformance.v1.MetadatumR\btrailers\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12S\n" +
	"\x0fstream_messages\x18\x06 \x03(\v2*.grpc.webnext.conformance.v1.StreamMessageR\x0estreamMessages\x12\x19\n" +
	"\bdelay_ms\x18\a \x01(\rR\adelayMs\x126\n" +
	"\x17oversize_response_bytes\x18\b \x01(\rR\x15oversizeResponseBytes\"D\n" +
	"\rStreamMessage\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x19\n" +
	"\bdelay_ms\x18\x02 \x01(\rR\adelayMs\"\x8a\x01\n" +
	"\fUnaryRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12`\n" +
	"\x13response_definition\x18\x02 \x01(\v2/.grpc.webnext.conformance.v1.ResponseDefinitionR\x12responseDefinition\"w\n" +
	"\x13ServerStreamRequest\x12`\n" +
	"\x13response_definition\x18\x01 \x01(\v2/.grpc.webnext.conformance.v1.ResponseDefinitionR\x12responseDefinition\"\x91\x01\n" +
	"\x13ClientStreamRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12`\n" +
	"\x13response_definition\x18\x02 \x01(\v2/.grpc.webnext.conformance.v1.ResponseDefinitionR\x12responseDefinition\"\xaf\x01\n" +
	"\x14ClientStreamResponse\x12I\n" +
	"\apayload\x18\x01 \x01(\v2/.grpc.webnext.conformance.v1.ConformancePayloadR\apayload\x12%\n" +
	"\x0ereceived_count\x18\x02 \x01(\rR\rreceivedCount\x12%\n" +
	"\x0ereceived_bytes\x18\x03 \x01(\x04R\rreceivedBytes\"\x8f\x01\n" +
	"\x11BidiStreamRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12`\n" +
	"\x13response_definition\x18\x02 \x01(\v2/.grpc.webnext.conformance.v1.ResponseDefinitionR\x12responseDefinition\"{\n" +
	"\x12ConformancePayload\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12K\n" +
	"\frequest_info\x18\x02 \x01(\v2(.grpc.webnext.conformance.v1.RequestInfoR\vrequestInfo\"A\n" +
	"\x18ClientStreamResponseInfo\x12%\n" +
	"\x0ereceived_count\x18\x01 \x01(\rR\rreceivedCount\"\x99\x01\n" +
	"\vRequestInfo\x12O\n" +
	"\x0frequest_headers\x18\x01 \x03(\v2&.grpc.webnext.conformance.v1.MetadatumR\x0erequestHeaders\x12%\n" +
	"\x0etimeout_millis\x18\x02 \x01(\rR\rtimeoutMillis\x12\x12\n" +
	"\x04json\x18\x03 \x01(\bR\x04json\"h\n" +
	"\tMetadatum\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\vascii_value\x18\x02 \x01(\tH\x00R\n" +
	"asciiValue\x12\x1d\n" +
	"\tbin_value\x18\x03 \x01(\fH\x00R\bbinValueB\a\n" +
	"\x05value2\xda\x06\n" +
	"\x12ConformanceService\x12y\n" +
	"\x05Unary\x12).grpc.webnext.conformance.v1.UnaryRequest\x1a/.grpc.webnext.conformance.v1.ConformancePayload\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/unary\x12\x91\x01\n" +
	"\fServerStream\x120.grpc.webnext.conformance.v1.ServerStreamRequest\x1a/.grpc.webnext.conformance.v1.ConformancePayload\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/server-stream0\x01\x12u\n" +
	"\fClientStream\x120.grpc.webnext.conformance.v1.ClientStreamRequest\x1a1.grpc.webnext.conformance.v1.ClientStreamResponse(\x01\x12q\n" +
	"\n" +
	"BidiStream\x12..grpc.webnext.conformance.v1.BidiStreamRequest\x1a/.grpc.webnext.conformance.v1.ConformancePayload(\x010\x01\x12\xaf\x01\n" +
	"\tRestUnary\x12-.grpc.webnext.conformance.v1.RestUnaryRequest\x1a/.grpc.webnext.conformance.v1.ConformancePayload\"B\x82\xd3\xe4\x93\x02<Z\r:\x01*\"\b/v1/restZ\x17:\x01*\"\x12/v1/rest/{payload}\x12\x12/v1/rest/{payload}\x12\x98\x01\n" +
	"\x10RestServerStream\x12..grpc.webnext.conformance.v1.RestStreamRequest\x1a/.grpc.webnext.conformance.v1.ConformancePayload\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/rest-stream/{payload}0\x01b\x06proto3"

var (
	file_conformance_proto_rawDescOnce sync.Once
	file_conformance_proto_rawDescData []byte
)

func file_conformance_proto_rawDescGZIP() []byte {
	file_conformance_proto_rawDescOnce.Do(func() {
		file_conformance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conformance_proto_rawDesc), len(file_conformance_proto_rawDesc)))
	})
	return file_conformance_proto_rawDescData
}

var file_conformance_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_conformance_proto_goTypes = []any{
	(*RestUnaryRequest)(nil),         // 0: grpc.webnext.conformance.v1.RestUnaryRequest
	(*RestStreamRequest)(nil),        // 1: grpc.webnext.conformance.v1.RestStreamRequest
	(*ResponseDefinition)(nil),       // 2: grpc.webnext.conformance.v1.ResponseDefinition
	(*StreamMessage)(nil),            // 3: grpc.webnext.conformance.v1.StreamMessage
	(*UnaryRequest)(nil),             // 4: grpc.webnext.conformance.v1.UnaryRequest
	(*ServerStreamRequest)(nil),      // 5: grpc.webnext.conformance.v1.ServerStreamRequest
	(*ClientStreamRequest)(nil),      // 6: grpc.webnext.conformance.v1.ClientStreamRequest
	(*ClientStreamResponse)(nil),     // 7: grpc.webnext.conformance.v1.ClientStreamResponse
	(*BidiStreamRequest)(nil),        // 8: grpc.webnext.conformance.v1.BidiStreamRequest
	(*ConformancePayload)(nil),       // 9: grpc.webnext.conformance.v1.ConformancePayload
	(*ClientStreamResponseInfo)(nil), // 10: grpc.webnext.conformance.v1.ClientStreamResponseInfo
	(*RequestInfo)(nil),              // 11: grpc.webnext.conformance.v1.RequestInfo
	(*Metadatum)(nil),                // 12: grpc.webnext.conformance.v1.Metadatum
}
var file_conformance_proto_depIdxs = []int32{
	12, // 0: grpc.webnext.conformance.v1.ResponseDefinition.headers:type_name -> grpc.webnext.conformance.v1.Metadatum
	12, // 1: grpc.webnext.conformance.v1.ResponseDefinition.trailers:type_name -> grpc.webnext.conformance.v1.Metadatum
	3,  // 2: grpc.webnext.conformance.v1.ResponseDefinition.stream_messages:type_name -> grpc.webnext.conformance.v1.StreamMessage
	2,  // 3: grpc.webnext.conformance.v1.UnaryRequest.response_definition:type_name -> grpc.webnext.conformance.v1.ResponseDefinition
	2,  // 4: grpc.webnext.conformance.v1.ServerStreamRequest.response_definition:type_name -> grpc.webnext.conformance.v1.ResponseDefinition
	2,  // 5: grpc.webnext.conformance.v1.ClientStreamRequest.response_definition:type_name -> grpc.webnext.conformance.v1.ResponseDefinition
	9,  // 6: grpc.webnext.conformance.v1.ClientStreamResponse.payload:type_name -> grpc.webnext.conformance.v1.ConformancePayload
	2,  // 7: grpc.webnext.conformance.v1.BidiStreamRequest.response_definition:type_name -> grpc.webnext.conformance.v1.ResponseDefinition
	11, // 8: grpc.webnext.conformance.v1.ConformancePayload.request_info:type_name -> grpc.webnext.conformance.v1.RequestInfo
	12, // 9: grpc.webnext.conformance.v1.RequestInfo.request_headers:type_name -> grpc.webnext.conformance.v1.Metadatum
	4,  // 10: grpc.webnext.conformance.v1.ConformanceService.Unary:input_type -> grpc.webnext.conformance.v1.UnaryRequest
	5,  // 11: grpc.webnext.conformance.v1.ConformanceService.ServerStream:input_type -> grpc.webnext.conformance.v1.ServerStreamRequest
	6,  // 12: grpc.webnext.conformance.v1.ConformanceService.ClientStream:input_type -> grpc.webnext.conformance.v1.ClientStreamRequest
	8,  // 13: grpc.webnext.conformance.v1.ConformanceService.BidiStream:input_type -> grpc.webnext.conformance.v1.BidiStreamRequest
	0,  // 14: grpc.webnext.conformance.v1.ConformanceService.RestUnary:input_type -> grpc.webnext.conformance.v1.RestUnaryRequest
	1,  // 15: grpc.webnext.conformance.v1.ConformanceService.RestServerStream:input_type -> grpc.webnext.conformance.v1.RestStreamRequest
	9,  // 16: grpc.webnext.conformance.v1.ConformanceService.Unary:output_type -> grpc.webnext.conformance.v1.ConformancePayload
	9,  // 17: grpc.webnext.conformance.v1.ConformanceService.ServerStream:output_type -> grpc.webnext.conformance.v1.ConformancePayload
	7,  // 18: grpc.webnext.conformance.v1.ConformanceService.ClientStream:output_type -> grpc.webnext.conformance.v1.ClientStreamResponse
	9,  // 19: grpc.webnext.conformance.v1.ConformanceService.BidiStream:output_type -> grpc.webnext.conformance.v1.ConformancePayload
	9,  // 20: grpc.webnext.conformance.v1.ConformanceService.RestUnary:output_type -> grpc.webnext.conformance.v1.ConformancePayload
	9,  // 21: grpc.webnext.conformance.v1.ConformanceService.RestServerStream:output_type -> grpc.webnext.conformance.v1.ConformancePayload
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_conformance_proto_init() }
func file_conformance_proto_init() {
	if File_conformance_proto != nil {
		return
	}
	file_conformance_proto_msgTypes[12].OneofWrappers = []any{
		(*Metadatum_AsciiValue)(nil),
		(*Metadatum_BinValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conformance_proto_rawDesc), len(file_conformance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_conformance_proto_goTypes,
		DependencyIndexes: file_conformance_proto_depIdxs,
		MessageInfos:      file_conformance_proto_msgTypes,
	}.Build()
	File_conformance_proto = out.File
	file_conformance_proto_goTypes = nil
	file_conformance_proto_depIdxs = nil
}
