// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: echo.proto

package testechopb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SleepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Millis        uint32                 `protobuf:"varint,1,opt,name=millis,proto3" json:"millis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SleepRequest) Reset() {
	*x = SleepRequest{}
	mi := &file_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SleepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SleepRequest) ProtoMessage() {}

func (x *SleepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SleepRequest.ProtoReflect.Descriptor instead.
func (*SleepRequest) Descriptor() ([]byte, []int) {
	return file_echo_proto_rawDescGZIP(), []int{0}
}

func (x *SleepRequest) GetMillis() uint32 {
	if x != nil {
		return x.Millis
	}
	return 0
}

type RepeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatRequest) Reset() {
	*x = RepeatRequest{}
	mi := &file_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatRequest) ProtoMessage() {}

func (x *RepeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatRequest.ProtoReflect.Descriptor instead.
func (*RepeatRequest) Descriptor() ([]byte, []int) {
	return file_echo_proto_rawDescGZIP(), []int{1}
}

func (x *RepeatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RepeatRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_echo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_echo_proto_rawDescGZIP(), []int{2}
}

func (x *EchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_echo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_echo_proto_rawDescGZIP(), []int{3}
}

func (x *EchoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_echo_proto protoreflect.FileDescriptor

const file_echo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"echo.proto\x12\aecho.v1\x1a\x1cgoogle/api/annotations.proto\"&\n" +
	"\fSleepRequest\x12\x16\n" +
	"\x06millis\x18\x01 \x01(\rR\x06millis\"?\n" +
	"\rRepeatRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"'\n" +
	"\vEchoRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\fEchoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x85\x04\n" +
	"\x04Echo\x12_\n" +
	"\x05Unary\x12\x14.echo.v1.EchoRequest\x1a\x15.echo.v1.EchoResponse\")\x82\xd3\xe4\x93\x02#:\x01*Z\x14\x12\x12/v1/echo/{message}\"\b/v1/echo\x129\n" +
	"\x06Stream\x12\x14.echo.v1.EchoRequest\x1a\x15.echo.v1.EchoResponse(\x010\x01\x12L\n" +
	"\x04Chat\x12\x14.echo.v1.EchoRequest\x1a\x15.echo.v1.EchoResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/chat(\x010\x01\x12W\n" +
	"\x06Repeat\x12\x16.echo.v1.RepeatRequest\x1a\x15.echo.v1.EchoResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/repeat/{message}0\x01\x125\n" +
	"\x04Hang\x12\x14.echo.v1.EchoRequest\x1a\x15.echo.v1.EchoResponse0\x01\x12H\n" +
	"\x05Sleep\x12\x15.echo.v1.SleepRequest\x1a\x15.echo.v1.EchoResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/sleep\x129\n" +
	"\n" +
	"FlakyUnary\x12\x14.echo.v1.EchoRequest\x1a\x15.echo.v1.EchoResponseb\x06proto3"

var (
	file_echo_proto_rawDescOnce sync.Once
	file_echo_proto_rawDescData []byte
)

func file_echo_proto_rawDescGZIP() []byte {
	file_echo_proto_rawDescOnce.Do(func() {
		file_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_echo_proto_rawDesc), len(file_echo_proto_rawDesc)))
	})
	return file_echo_proto_rawDescData
}

var file_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_echo_proto_goTypes = []any{
	(*SleepRequest)(nil),  // 0: echo.v1.SleepRequest
	(*RepeatRequest)(nil), // 1: echo.v1.RepeatRequest
	(*EchoRequest)(nil),   // 2: echo.v1.EchoRequest
	(*EchoResponse)(nil),  // 3: echo.v1.EchoResponse
}
var file_echo_proto_depIdxs = []int32{
	2, // 0: echo.v1.Echo.Unary:input_type -> echo.v1.EchoRequest
	2, // 1: echo.v1.Echo.Stream:input_type -> echo.v1.EchoRequest
	2, // 2: echo.v1.Echo.Chat:input_type -> echo.v1.EchoRequest
	1, // 3: echo.v1.Echo.Repeat:input_type -> echo.v1.RepeatRequest
	2, // 4: echo.v1.Echo.Hang:input_type -> echo.v1.EchoRequest
	0, // 5: echo.v1.Echo.Sleep:input_type -> echo.v1.SleepRequest
	2, // 6: echo.v1.Echo.FlakyUnary:input_type -> echo.v1.EchoRequest
	3, // 7: echo.v1.Echo.Unary:output_type -> echo.v1.EchoResponse
	3, // 8: echo.v1.Echo.Stream:output_type -> echo.v1.EchoResponse
	3, // 9: echo.v1.Echo.Chat:output_type -> echo.v1.EchoResponse
	3, // 10: echo.v1.Echo.Repeat:output_type -> echo.v1.EchoResponse
	3, // 11: echo.v1.Echo.Hang:output_type -> echo.v1.EchoResponse
	3, // 12: echo.v1.Echo.Sleep:output_type -> echo.v1.EchoResponse
	3, // 13: echo.v1.Echo.FlakyUnary:output_type -> echo.v1.EchoResponse
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_echo_proto_init() }
func file_echo_proto_init() {
	if File_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echo_proto_rawDesc), len(file_echo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_echo_proto_goTypes,
		DependencyIndexes: file_echo_proto_depIdxs,
		MessageInfos:      file_echo_proto_msgTypes,
	}.Build()
	File_echo_proto = out.File
	file_echo_proto_goTypes = nil
	file_echo_proto_depIdxs = nil
}
