// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: echo.proto

package testechopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Echo_Unary_FullMethodName      = "/echo.v1.Echo/Unary"
	Echo_Stream_FullMethodName     = "/echo.v1.Echo/Stream"
	Echo_Chat_FullMethodName       = "/echo.v1.Echo/Chat"
	Echo_Repeat_FullMethodName     = "/echo.v1.Echo/Repeat"
	Echo_Hang_FullMethodName       = "/echo.v1.Echo/Hang"
	Echo_Sleep_FullMethodName      = "/echo.v1.Echo/Sleep"
	Echo_FlakyUnary_FullMethodName = "/echo.v1.Echo/FlakyUnary"
)

// EchoClient is the client API for Echo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EchoClient interface {
	// Unary: returns the same message. Also exposed as REST via HTTP transcoding:
	//
	//	POST /v1/echo          { "message": "hi" }
	//	GET  /v1/echo/{message}
	Unary(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	// Bidi streaming: echoes each message back. (Un-annotated: reached only over the
	// main WebSocket surface.)
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EchoRequest, EchoResponse], error)
	// Bidi streaming echo, exposed as a REST-transcoded stream:
	//
	//	POST /v1/chat   (each frame's JSON body is a request message)
	Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EchoRequest, EchoResponse], error)
	// Server streaming that emits `message` `count` times, then completes. REST:
	//
	//	GET /v1/repeat/{message}?count=N  (request built entirely from the URL)
	Repeat(ctx context.Context, in *RepeatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EchoResponse], error)
	// Server streaming that emits one message then hangs forever; used to observe
	// upstream cancellation when the client resets/disconnects.
	Hang(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EchoResponse], error)
	// Unary that sleeps `millis` before replying; used to exercise deadlines.
	// REST: GET /v1/sleep?millis=N  (numeric field bound from a query param).
	Sleep(ctx context.Context, in *SleepRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	// Unary that fails with UNAVAILABLE a preset number of times, then succeeds;
	// used to exercise retry.
	FlakyUnary(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
}

type echoClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoClient(cc grpc.ClientConnInterface) EchoClient {
	return &echoClient{cc}
}

func (c *echoClient) Unary(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, Echo_Unary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EchoRequest, EchoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Echo_ServiceDesc.Streams[0], Echo_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EchoRequest, EchoResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_StreamClient = grpc.BidiStreamingClient[EchoRequest, EchoResponse]

func (c *echoClient) Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EchoRequest, EchoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Echo_ServiceDesc.Streams[1], Echo_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EchoRequest, EchoResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_ChatClient = grpc.BidiStreamingClient[EchoRequest, EchoResponse]

func (c *echoClient) Repeat(ctx context.Context, in *RepeatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EchoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Echo_ServiceDesc.Streams[2], Echo_Repeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RepeatRequest, EchoResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_RepeatClient = grpc.ServerStreamingClient[EchoResponse]

func (c *echoClient) Hang(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EchoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Echo_ServiceDesc.Streams[3], Echo_Hang_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EchoRequest, EchoResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_HangClient = grpc.ServerStreamingClient[EchoResponse]

func (c *echoClient) Sleep(ctx context.Context, in *SleepRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, Echo_Sleep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoClient) FlakyUnary(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, Echo_FlakyUnary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EchoServer is the server API for Echo service.
// All implementations must embed UnimplementedEchoServer
// for forward compatibility.
type EchoServer interface {
	// Unary: returns the same message. Also exposed as REST via HTTP transcoding:
	//
	//	POST /v1/echo          { "message": "hi" }
	//	GET  /v1/echo/{message}
	Unary(context.Context, *EchoRequest) (*EchoResponse, error)
	// Bidi streaming: echoes each message back. (Un-annotated: reached only over the
	// main WebSocket surface.)
	Stream(grpc.BidiStreamingServer[EchoRequest, EchoResponse]) error
	// Bidi streaming echo, exposed as a REST-transcoded stream:
	//
	//	POST /v1/chat   (each frame's JSON body is a request message)
	Chat(grpc.BidiStreamingServer[EchoRequest, EchoResponse]) error
	// Server streaming that emits `message` `count` times, then completes. REST:
	//
	//	GET /v1/repeat/{message}?count=N  (request built entirely from the URL)
	Repeat(*RepeatRequest, grpc.ServerStreamingServer[EchoResponse]) error
	// Server streaming that emits one message then hangs forever; used to observe
	// upstream cancellation when the client resets/disconnects.
	Hang(*EchoRequest, grpc.ServerStreamingServer[EchoResponse]) error
	// Unary that sleeps `millis` before replying; used to exercise deadlines.
	// REST: GET /v1/sleep?millis=N  (numeric field bound from a query param).
	Sleep(context.Context, *SleepRequest) (*EchoResponse, error)
	// Unary that fails with UNAVAILABLE a preset number of times, then succeeds;
	// used to exercise retry.
	FlakyUnary(context.Context, *EchoRequest) (*EchoResponse, error)
	mustEmbedUnimplementedEchoServer()
}

// UnimplementedEchoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEchoServer struct{}

func (UnimplementedEchoServer) Unary(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unary not implemented")
}
func (UnimplementedEchoServer) Stream(grpc.BidiStreamingServer[EchoRequest, EchoResponse]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedEchoServer) Chat(grpc.BidiStreamingServer[EchoRequest, EchoResponse]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedEchoServer) Repeat(*RepeatRequest, grpc.ServerStreamingServer[EchoResponse]) error {
	return status.Error(codes.Unimplemented, "method Repeat not implemented")
}
func (UnimplementedEchoServer) Hang(*EchoRequest, grpc.ServerStreamingServer[EchoResponse]) error {
	return status.Error(codes.Unimplemented, "method Hang not implemented")
}
func (UnimplementedEchoServer) Sleep(context.Context, *SleepRequest) (*EchoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sleep not implemented")
}
func (UnimplementedEchoServer) FlakyUnary(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FlakyUnary not implemented")
}
func (UnimplementedEchoServer) mustEmbedUnimplementedEchoServer() {}
func (UnimplementedEchoServer) testEmbeddedByValue()              {}

// UnsafeEchoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EchoServer will
// result in compilation errors.
type UnsafeEchoServer interface {
	mustEmbedUnimplementedEchoServer()
}

func RegisterEchoServer(s grpc.ServiceRegistrar, srv EchoServer) {
	// If the following call panics, it indicates UnimplementedEchoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Echo_ServiceDesc, srv)
}

func _Echo_Unary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).Unary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Echo_Unary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).Unary(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echo_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EchoServer).Stream(&grpc.GenericServerStream[EchoRequest, EchoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_StreamServer = grpc.BidiStreamingServer[EchoRequest, EchoResponse]

func _Echo_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EchoServer).Chat(&grpc.GenericServerStream[EchoRequest, EchoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_ChatServer = grpc.BidiStreamingServer[EchoRequest, EchoResponse]

func _Echo_Repeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RepeatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EchoServer).Repeat(m, &grpc.GenericServerStream[RepeatRequest, EchoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_RepeatServer = grpc.ServerStreamingServer[EchoResponse]

func _Echo_Hang_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EchoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EchoServer).Hang(m, &grpc.GenericServerStream[EchoRequest, EchoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_HangServer = grpc.ServerStreamingServer[EchoResponse]

func _Echo_Sleep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SleepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).Sleep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Echo_Sleep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).Sleep(ctx, req.(*SleepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echo_FlakyUnary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).FlakyUnary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Echo_FlakyUnary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).FlakyUnary(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Echo_ServiceDesc is the grpc.ServiceDesc for Echo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Echo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "echo.v1.Echo",
	HandlerType: (*EchoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unary",
			Handler:    _Echo_Unary_Handler,
		},
		{
			MethodName: "Sleep",
			Handler:    _Echo_Sleep_Handler,
		},
		{
			MethodName: "FlakyUnary",
			Handler:    _Echo_FlakyUnary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Echo_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Chat",
			Handler:       _Echo_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Repeat",
			Handler:       _Echo_Repeat_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Hang",
			Handler:       _Echo_Hang_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "echo.proto",
}
